//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")
    /// Resource file `Xcode.gitignore`.
    static let xcodeGitignore = Rswift.FileResource(bundle: R.hostingBundle, name: "Xcode", pathExtension: "gitignore")
    
    /// `bundle.url(forResource: "GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Xcode", withExtension: "gitignore")`
    static func xcodeGitignore(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.xcodeGitignore
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 7 images.
  struct image {
    /// Image `add`.
    static let add = Rswift.ImageResource(bundle: R.hostingBundle, name: "add")
    /// Image `close-icon`.
    static let closeIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "close-icon")
    /// Image `email-icon`.
    static let emailIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "email-icon")
    /// Image `illustration2`.
    static let illustration2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "illustration2")
    /// Image `placeholder`.
    static let placeholder = Rswift.ImageResource(bundle: R.hostingBundle, name: "placeholder")
    /// Image `right-arrow`.
    static let rightArrow = Rswift.ImageResource(bundle: R.hostingBundle, name: "right-arrow")
    /// Image `trees`.
    static let trees = Rswift.ImageResource(bundle: R.hostingBundle, name: "trees")
    
    /// `UIImage(named: "add", bundle: ..., traitCollection: ...)`
    static func add(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.add, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "close-icon", bundle: ..., traitCollection: ...)`
    static func closeIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.closeIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "email-icon", bundle: ..., traitCollection: ...)`
    static func emailIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.emailIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "illustration2", bundle: ..., traitCollection: ...)`
    static func illustration2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.illustration2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "placeholder", bundle: ..., traitCollection: ...)`
    static func placeholder(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.placeholder, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "right-arrow", bundle: ..., traitCollection: ...)`
    static func rightArrow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.rightArrow, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "trees", bundle: ..., traitCollection: ...)`
    static func trees(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.trees, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 8 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `JobsCell`.
    static let jobsCell: Rswift.ReuseIdentifier<JobsCell> = Rswift.ReuseIdentifier(identifier: "JobsCell")
    /// Reuse identifier `TopicAlbumsTableViewCell`.
    static let topicAlbumsTableViewCell: Rswift.ReuseIdentifier<TopicAlbumsTableViewCell> = Rswift.ReuseIdentifier(identifier: "TopicAlbumsTableViewCell")
    /// Reuse identifier `TopicTableViewCell`.
    static let topicTableViewCell: Rswift.ReuseIdentifier<TopicTableViewCell> = Rswift.ReuseIdentifier(identifier: "TopicTableViewCell")
    /// Reuse identifier `cell`.
    static let cell: Rswift.ReuseIdentifier<JobCell> = Rswift.ReuseIdentifier(identifier: "cell")
    /// Reuse identifier `imageCell`.
    static let imageCell: Rswift.ReuseIdentifier<ImageCellController> = Rswift.ReuseIdentifier(identifier: "imageCell")
    /// Reuse identifier `singleDetailAlbumCell`.
    static let singleDetailAlbumCell: Rswift.ReuseIdentifier<SingleDetailAlbumCell> = Rswift.ReuseIdentifier(identifier: "singleDetailAlbumCell")
    /// Reuse identifier `singleLineActionCell`.
    static let singleLineActionCell: Rswift.ReuseIdentifier<SingleLineActionCell> = Rswift.ReuseIdentifier(identifier: "singleLineActionCell")
    /// Reuse identifier `singleLineActionController`.
    static let singleLineActionController: Rswift.ReuseIdentifier<SingleLineActionController> = Rswift.ReuseIdentifier(identifier: "singleLineActionController")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 10 view controllers.
  struct segue {
    /// This struct is generated for `AddJobController`, and contains static references to 1 segues.
    struct addJobController {
      /// Segue identifier `segueMission`.
      static let segueMission: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AddJobController, AddMissioneController> = Rswift.StoryboardSegueIdentifier(identifier: "segueMission")
      
      /// Optionally returns a typed version of segue `segueMission`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueMission(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AddJobController, AddMissioneController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.addJobController.segueMission, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `AlbumItemController`, and contains static references to 1 segues.
    struct albumItemController {
      /// Segue identifier `segueToDetails`.
      static let segueToDetails: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AlbumItemController, AlbumItemDetailsController> = Rswift.StoryboardSegueIdentifier(identifier: "segueToDetails")
      
      /// Optionally returns a typed version of segue `segueToDetails`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueToDetails(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AlbumItemController, AlbumItemDetailsController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.albumItemController.segueToDetails, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `ContractController`, and contains static references to 1 segues.
    struct contractController {
      /// Segue identifier `segueJobs`.
      static let segueJobs: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, ContractController, JobsListViewController> = Rswift.StoryboardSegueIdentifier(identifier: "segueJobs")
      
      /// Optionally returns a typed version of segue `segueJobs`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueJobs(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, ContractController, JobsListViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.contractController.segueJobs, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `JobDetailsViewController`, and contains static references to 1 segues.
    struct jobDetailsViewController {
      /// Segue identifier `segueToAlbumSpecs`.
      static let segueToAlbumSpecs: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, JobDetailsViewController, AlbumItemController> = Rswift.StoryboardSegueIdentifier(identifier: "segueToAlbumSpecs")
      
      /// Optionally returns a typed version of segue `segueToAlbumSpecs`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueToAlbumSpecs(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, JobDetailsViewController, AlbumItemController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.jobDetailsViewController.segueToAlbumSpecs, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `JobsListViewController`, and contains static references to 2 segues.
    struct jobsListViewController {
      /// Segue identifier `segueToDetails`.
      static let segueToDetails: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, JobsListViewController, JobDetailsViewController> = Rswift.StoryboardSegueIdentifier(identifier: "segueToDetails")
      /// Segue identifier `toAddSegue`.
      static let toAddSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, JobsListViewController, AddJobController> = Rswift.StoryboardSegueIdentifier(identifier: "toAddSegue")
      
      /// Optionally returns a typed version of segue `segueToDetails`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueToDetails(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, JobsListViewController, JobDetailsViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.jobsListViewController.segueToDetails, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `toAddSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func toAddSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, JobsListViewController, AddJobController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.jobsListViewController.toAddSegue, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `LaunchScreenController`, and contains static references to 2 segues.
    struct launchScreenController {
      /// Segue identifier `segueToAuth`.
      static let segueToAuth: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, LaunchScreenController, AuthScreenController> = Rswift.StoryboardSegueIdentifier(identifier: "segueToAuth")
      /// Segue identifier `segueToHome`.
      static let segueToHome: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, LaunchScreenController, JobsListViewController> = Rswift.StoryboardSegueIdentifier(identifier: "segueToHome")
      
      /// Optionally returns a typed version of segue `segueToAuth`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueToAuth(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, LaunchScreenController, AuthScreenController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.launchScreenController.segueToAuth, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `segueToHome`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueToHome(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, LaunchScreenController, JobsListViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.launchScreenController.segueToHome, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `LoginViewController`, and contains static references to 1 segues.
    struct loginViewController {
      /// Segue identifier `segueToJobs`.
      static let segueToJobs: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, LoginViewController, JobsListViewController> = Rswift.StoryboardSegueIdentifier(identifier: "segueToJobs")
      
      /// Optionally returns a typed version of segue `segueToJobs`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueToJobs(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, LoginViewController, JobsListViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.loginViewController.segueToJobs, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `OptionsViewController`, and contains static references to 3 segues.
    struct optionsViewController {
      /// Segue identifier `authSegue`.
      static let authSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, OptionsViewController, AuthScreenController> = Rswift.StoryboardSegueIdentifier(identifier: "authSegue")
      /// Segue identifier `toCreditSegue`.
      static let toCreditSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, OptionsViewController, CreditsViewController> = Rswift.StoryboardSegueIdentifier(identifier: "toCreditSegue")
      /// Segue identifier `toInfoSegue`.
      static let toInfoSegue: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, OptionsViewController, UserInfoViewController> = Rswift.StoryboardSegueIdentifier(identifier: "toInfoSegue")
      
      /// Optionally returns a typed version of segue `authSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func authSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, OptionsViewController, AuthScreenController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.optionsViewController.authSegue, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `toCreditSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func toCreditSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, OptionsViewController, CreditsViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.optionsViewController.toCreditSegue, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `toInfoSegue`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func toInfoSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, OptionsViewController, UserInfoViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.optionsViewController.toInfoSegue, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `SignupController`, and contains static references to 1 segues.
    struct signupController {
      /// Segue identifier `segueToUserInfo`.
      static let segueToUserInfo: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, SignupController, UserInfoController> = Rswift.StoryboardSegueIdentifier(identifier: "segueToUserInfo")
      
      /// Optionally returns a typed version of segue `segueToUserInfo`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueToUserInfo(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, SignupController, UserInfoController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.signupController.segueToUserInfo, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `UserInfoController`, and contains static references to 1 segues.
    struct userInfoController {
      /// Segue identifier `segueToTerms`.
      static let segueToTerms: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, UserInfoController, ContractController> = Rswift.StoryboardSegueIdentifier(identifier: "segueToTerms")
      
      /// Optionally returns a typed version of segue `segueToTerms`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func segueToTerms(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, UserInfoController, ContractController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.userInfoController.segueToTerms, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 11 storyboards.
  struct storyboard {
    /// Storyboard `AddAlbum`.
    static let addAlbum = _R.storyboard.addAlbum()
    /// Storyboard `AddJob`.
    static let addJob = _R.storyboard.addJob()
    /// Storyboard `AlbumItem`.
    static let albumItem = _R.storyboard.albumItem()
    /// Storyboard `AuthScreen`.
    static let authScreen = _R.storyboard.authScreen()
    /// Storyboard `JobDetails`.
    static let jobDetails = _R.storyboard.jobDetails()
    /// Storyboard `Jobs`.
    static let jobs = _R.storyboard.jobs()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Login`.
    static let login = _R.storyboard.login()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `Options`.
    static let options = _R.storyboard.options()
    /// Storyboard `Signup`.
    static let signup = _R.storyboard.signup()
    
    /// `UIStoryboard(name: "AddAlbum", bundle: ...)`
    static func addAlbum(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.addAlbum)
    }
    
    /// `UIStoryboard(name: "AddJob", bundle: ...)`
    static func addJob(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.addJob)
    }
    
    /// `UIStoryboard(name: "AlbumItem", bundle: ...)`
    static func albumItem(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.albumItem)
    }
    
    /// `UIStoryboard(name: "AuthScreen", bundle: ...)`
    static func authScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.authScreen)
    }
    
    /// `UIStoryboard(name: "JobDetails", bundle: ...)`
    static func jobDetails(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.jobDetails)
    }
    
    /// `UIStoryboard(name: "Jobs", bundle: ...)`
    static func jobs(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.jobs)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Login", bundle: ...)`
    static func login(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.login)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "Options", bundle: ...)`
    static func options(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.options)
    }
    
    /// `UIStoryboard(name: "Signup", bundle: ...)`
    static func signup(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.signup)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try signup.validate()
      try jobDetails.validate()
      try authScreen.validate()
      try jobs.validate()
      try addAlbum.validate()
      try login.validate()
      try albumItem.validate()
      try launchScreen.validate()
      try addJob.validate()
      try main.validate()
      try options.validate()
    }
    
    struct addAlbum: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = AddAlbumController
      
      let bundle = R.hostingBundle
      let name = "AddAlbum"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct addJob: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = AddJobController
      
      let bundle = R.hostingBundle
      let name = "AddJob"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct albumItem: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = AlbumItemController
      
      let bundle = R.hostingBundle
      let name = "AlbumItem"
      
      static func validate() throws {
        if UIKit.UIImage(named: "right-arrow") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'right-arrow' is used in storyboard 'AlbumItem', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct authScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = AuthScreenController
      
      let authScreen = StoryboardViewControllerResource<AuthScreenController>(identifier: "AuthScreen")
      let bundle = R.hostingBundle
      let name = "AuthScreen"
      
      func authScreen(_: Void = ()) -> AuthScreenController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: authScreen)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "trees") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'trees' is used in storyboard 'AuthScreen', but couldn't be loaded.") }
        if UIKit.UIImage(named: "email-icon") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'email-icon' is used in storyboard 'AuthScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.authScreen().authScreen() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'authScreen' could not be loaded from storyboard 'AuthScreen' as 'AuthScreenController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct jobDetails: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = JobDetailsViewController
      
      let bundle = R.hostingBundle
      let name = "JobDetails"
      
      static func validate() throws {
        if UIKit.UIImage(named: "right-arrow") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'right-arrow' is used in storyboard 'JobDetails', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct jobs: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = JobsListViewController
      
      let bundle = R.hostingBundle
      let name = "Jobs"
      
      static func validate() throws {
        if UIKit.UIImage(named: "add") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'add' is used in storyboard 'Jobs', but couldn't be loaded.") }
        if UIKit.UIImage(named: "illustration2") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'illustration2' is used in storyboard 'Jobs', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct login: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = LoginViewController
      
      let bundle = R.hostingBundle
      let name = "Login"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct options: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = OptionsViewController
      
      let bundle = R.hostingBundle
      let name = "Options"
      
      static func validate() throws {
        if UIKit.UIImage(named: "placeholder") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'placeholder' is used in storyboard 'Options', but couldn't be loaded.") }
        if UIKit.UIImage(named: "right-arrow") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'right-arrow' is used in storyboard 'Options', but couldn't be loaded.") }
        if UIKit.UIImage(named: "illustration2") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'illustration2' is used in storyboard 'Options', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct signup: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = SignupController
      
      let bundle = R.hostingBundle
      let name = "Signup"
      let termsController = StoryboardViewControllerResource<ContractController>(identifier: "TermsController")
      let userInfoController = StoryboardViewControllerResource<UserInfoController>(identifier: "UserInfoController")
      
      func termsController(_: Void = ()) -> ContractController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: termsController)
      }
      
      func userInfoController(_: Void = ()) -> UserInfoController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: userInfoController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "placeholder") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'placeholder' is used in storyboard 'Signup', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.signup().userInfoController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'userInfoController' could not be loaded from storyboard 'Signup' as 'UserInfoController'.") }
        if _R.storyboard.signup().termsController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'termsController' could not be loaded from storyboard 'Signup' as 'ContractController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
